pipelines:
  - name: barebones_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: app
        execution:
          onExecute:
            - printenv
